services:
  web:
    container_name: "django"
    build: .
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
  db:
    container_name: "sql"
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    
  
volumes: 
    db_data: